export const ROUND1_QUESTIONS = [
    { id: 1, text: "If 5 machines take 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?", options: ["100 minutes", "5 minutes", "1 minute", "20 minutes"], answer: 1 },
    { id: 2, text: "Which number comes next: 2, 6, 12, 20, 30, ...?", options: ["40", "42", "38", "44"], answer: 1 },
    { id: 3, text: "Binary representation of the decimal number 10 is:", options: ["1001", "1100", "1010", "1000"], answer: 2 },
    { id: 4, text: "What is the time complexity of binary search?", options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"], answer: 1 },
    { id: 5, text: "Which data structure uses LIFO (Last In First Out)?", options: ["Queue", "Array", "Stack", "Tree"], answer: 2 },
    { id: 6, text: "Identify the odd one out: Linux, Windows, Python, macOS", options: ["Linux", "Windows", "Python", "macOS"], answer: 2 },
    { id: 7, text: "A byte consists of how many bits?", options: ["4", "8", "16", "32"], answer: 1 },
    { id: 8, text: "Which logic gate returns TRUE only if both inputs are TRUE?", options: ["OR", "NAND", "XOR", "AND"], answer: 3 },
    { id: 9, text: "What comes next in the sequence: A, C, F, J, O, ...?", options: ["T", "U", "S", "V"], answer: 1 },
    { id: 10, text: "In a race, you overtake the person in 2nd place. What position are you in?", options: ["1st", "2nd", "3rd", "Last"], answer: 1 },
    { id: 11, text: "Which protocol is used to send emails?", options: ["HTTP", "FTP", "SMTP", "POP3"], answer: 2 },
    { id: 12, text: "Which color is #00FF00?", options: ["Red", "Green", "Blue", "Yellow"], answer: 1 },
    { id: 13, text: "How many nodes are in a full binary tree with depth 3?", options: ["7", "8", "6", "15"], answer: 0 },
    { id: 14, text: "Which sort is generally fastest for large random datasets?", options: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Quick Sort"], answer: 3 },
    { id: 15, text: "Git command to upload changes to remote?", options: ["git save", "git upload", "git push", "git commit"], answer: 2 },
    { id: 16, text: "What does SQL stand for?", options: ["Structured Question Language", "Structured Query Language", "Simple Query Logic", "Standard Query Link"], answer: 1 },
    { id: 17, text: "Hexadecimal 'F' equals decimal:", options: ["16", "15", "14", "10"], answer: 1 },
    { id: 18, text: "Which is NOT a programming language?", options: ["HTML", "Java", "C++", "Python"], answer: 0 },
    { id: 19, text: "Logical relation: IF A=B and B=C, then:", options: ["A > C", "A < C", "A = C", "A != C"], answer: 2 },
    { id: 20, text: "Debug this: INT x = 5 / 0;", options: ["Returns 0", "Returns Infinity", "Runtime Error", "Compiler Error"], answer: 2 },
];

export const ROUND3_QUESTIONS = [
    { id: 1, text: "Which AI model is developed by OpenAI?", options: ["Llama", "Gemini", "GPT-4", "Claude"], answer: 2 },
    { id: 2, text: "What does AWS stand for?", options: ["Amazon Web Services", "Apple Web System", "Advanced Web Solutions", "Automated Web Server"], answer: 0 },
    { id: 3, text: "Which protocol is use for secure browsing?", options: ["HTTP", "FTP", "SSH", "HTTPS"], answer: 3 },
    { id: 4, text: "The 'brain' of the computer is:", options: ["RAM", "GPU", "CPU", "Motherboard"], answer: 2 },
    { id: 5, text: "Who is considered the father of the computer?", options: ["Alan Turing", "Charles Babbage", "Steve Jobs", "Bill Gates"], answer: 1 },
    { id: 6, text: "Which is a NoSQL database?", options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"], answer: 2 },
    { id: 7, text: "What is the primary function of an OS?", options: ["Compile code", "Manage resources", "Design websites", "Protect from viruses"], answer: 1 },
    { id: 8, text: "First computer programmer?", options: ["Ada Lovelace", "Grace Hopper", "Margaret Hamilton", "Katherine Johnson"], answer: 0 },
    { id: 9, text: "What year was the World Wide Web invented?", options: ["1983", "1989", "1995", "2000"], answer: 1 },
    { id: 10, text: "Which cloud provider belongs to Google?", options: ["Azure", "AWS", "DigitalOcean", "GCP"], answer: 3 },
    { id: 11, text: "What does 'Phishing' refer to?", options: ["Fishing game", "Identity Theft Scam", "Network Testing", "Database Optimization"], answer: 1 },
    { id: 12, text: "Which is a containerization tool?", options: ["Kubernetes", "Docker", "Ansible", "Jenkins"], answer: 1 },
    { id: 13, text: "What is 'Blockchain' primarily known for?", options: ["Centralized Storage", "Decentralized Ledger", "Cloud Computing", "AI Processing"], answer: 1 },
    { id: 14, text: "Which allows running multiple OS on one machine?", options: ["Virtualization", "Compilation", "Interpretation", "Segmentation"], answer: 0 },
    { id: 15, text: "What port does HTTP commonly use?", options: ["21", "22", "80", "443"], answer: 2 },
    { id: 16, text: "Who co-founded Microsoft?", options: ["Steve Wozniak", "Paul Allen", "Larry Page", "Elon Musk"], answer: 1 },
    { id: 17, text: "Which is a statically typed language?", options: ["Python", "JavaScript", "Java", "Ruby"], answer: 2 },
    { id: 18, text: "What does 'IoT' stand for?", options: ["Internet of Tokens", "Internet of Things", "Input of Technology", "Integrator of Tools"], answer: 1 },
    { id: 19, text: "Which company owns GitHub?", options: ["Google", "Facebook", "Microsoft", "Amazon"], answer: 2 },
    { id: 20, text: "What is the complexity of accessing an array index?", options: ["O(n)", "O(1)", "O(log n)", "O(n^2)"], answer: 1 },
];
